### ISSUE TITLE
net-im/telegram-desktop fails to build on gentoo gcc 8.3.0

### ISSUE THREAD

**Issue by evilbulgarian** [reagentoo/gentoo-overlay#21]
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/base/flat_set.h:560:7: note:   candidate expects 1 argument, 2 provided
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/base/flat_set.h:560:7: note: candidate: 'base::flat_set<int>::flat_set(base::flat_set<int>&&)'
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/base/flat_set.h:560:7: note:   candidate expects 1 argument, 2 provided
also patch clang-optonal-tmpfix.patch fails to apply,

/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/apiwrap.cpp:1603:29: error: unable to deduce 'auto&&' from 'adding'
  for (const auto addingId : adding) {
                             ^~~~~~
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/apiwrap.cpp: In member function 'void ApiWrap::sendPollVotes(FullMsgId, const std::vector<QByteArray>&)':
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/apiwrap.cpp:5502:11: error: 'back_inserter' is not a member of 'ranges'
   ranges::back_inserter(prepared),
           ^~~~~~~~~~~~~
/tmp/portage/net-im/telegram-desktop-9999/work/telegram-desktop-9999/Telegram/SourceFiles/apiwrap.cpp:5502:11: note: suggested alternative:
In file included from /usr/lib/gcc/x86_64-pc-linux-gnu/8.3.0/include/g++-v8/bits/stl_algobase.h:67,
